(cl:defpackage RYDS-srv
  (:use )
  (:export
   "HANDLER"
   "<HANDLER-REQUEST>"
   "HANDLER-REQUEST"
   "<HANDLER-RESPONSE>"
   "HANDLER-RESPONSE"
   "TEST"
   "<TEST-REQUEST>"
   "TEST-REQUEST"
   "<TEST-RESPONSE>"
   "TEST-RESPONSE"
   "COMPAREHISTO"
   "<COMPAREHISTO-REQUEST>"
   "COMPAREHISTO-REQUEST"
   "<COMPAREHISTO-RESPONSE>"
   "COMPAREHISTO-RESPONSE"
  ))

